name: Build and deploy .Net app to an Azure Web App

env:
  AZURE_AuthAPI_Name: 'pcmauthapi'   
  AZURE_CouponAPI_Name: 'pcmcouponapi'
  AZURE_EmailAPI_Name: 'pcmemailapi'
  AZURE_ProductAPI_Name: 'pcmproductapi'
  AZURE_ShoppingCartAPI_Name: 'pcmshoppingcartapi'
  AZURE_Web_Name: 'productcouponmanagement'
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x'                 # set this to the .NET Core version to use
  Path_Auth_API: 'Services.AuthAPI'
  Path_Coupon_API: 'Services.CouponAPI'
  Path_Email_API: 'Services.EmailAPI'
  Path_Product_API: 'Services.ProductAPI'
  Path_ShoppingCart_API: 'Services.ShoppingCartAPI'
  Path_Web: 'Web'
  
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: echo workspace
        run: echo "workspace - ${{ github.workspace }}"
        
      - name: dotnet publish auth api
        run: dotnet publish ./${{env.Path_Auth_API}}/ -c Release -o ${{ github.workspace }}/${{env.Path_Auth_API}}/myapp

      - name: dotnet publish coupon api
        run: dotnet publish ./${{env.Path_Coupon_API}}/ -c Release -o ${{ github.workspace }}/${{env.Path_Coupon_API}}/myapp

      - name: dotnet publish email api
        run: dotnet publish ./${{env.Path_Email_API}}/ -c Release -o ${{ github.workspace }}/${{env.Path_Email_API}}/myapp

      - name: dotnet publish product api
        run: dotnet publish ./${{env.Path_Product_API}}/ -c Release -o ${{ github.workspace }}/${{env.Path_Product_API}}/myapp

      - name: dotnet publish shopping cart api
        run: dotnet publish ./${{env.Path_ShoppingCart_API}}/ -c Release -o ${{ github.workspace }}/${{env.Path_ShoppingCart_API}}/myapp

      - name: dotnet publish web
        run: dotnet publish ./${{env.Path_Web}}/ -c Release -o ${{ github.workspace }}/${{env.Path_Web}}/myapp
        
  upload:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Upload artifact auth api
        uses: actions/upload-artifact@v4
        with:
          name: auth-api
          path: ${{ github.workspace }}/${{env.Path_Auth_API}}/myapp

      - name: Upload artifact coupon api
        uses: actions/upload-artifact@v4
        with:
          name: coupon-api
          path: ${{ github.workspace }}/${{env.Path_Coupon_API}}/myapp

      - name: Upload artifact email api
        uses: actions/upload-artifact@v4
        with:
          name: email-api
          path: ${{ github.workspace }}/${{env.Path_Email_API}}/myapp

      - name: Upload artifact product api
        uses: actions/upload-artifact@v4
        with:
          name: product-api
          path: ${{ github.workspace }}/${{env.Path_Product_API}}/myapp

      - name: Upload artifact shoppingcart api
        uses: actions/upload-artifact@v4
        with:
          name: shoppingcart-api
          path: ${{ github.workspace }}/${{env.Path_ShoppingCart_API}}/myapp

      - name: Upload artifact web
        uses: actions/upload-artifact@v4
        with:
          name: web-ui
          path: ${{ github.workspace }}/${{env.Path_Web}}/myapp
