name: Build and deploy .Net app to an Azure Web App

env:
  AZURE_AuthAPI_Name: 'pcmauthapi'   
  AZURE_CouponAPI_Name: 'pcmcouponapi'
  AZURE_EmailAPI_Name: 'pcmemailapi'
  AZURE_ProductAPI_Name: 'pcmproductapi'
  AZURE_ShoppingCartAPI_Name: 'pcmshoppingcartapi'
  AZURE_Web_Name: 'productcouponmanagement'
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x'                 # set this to the .NET Core version to use
  Path_Auth_API: 'Services.AuthAPI'
  Path_Coupon_API: 'Services.CouponAPI'
  Path_Email_API: 'Services.EmailAPI'
  Path_Product_API: 'Services.ProductAPI'
  Path_ShoppingCart_API: 'Services.ShoppingCartAPI'
  Path_Web: 'Web'
  
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: echo workspace
        run: echo "workspace - ${{ github.workspace }}"
        
      - name: dotnet publish auth api
        run: dotnet publish ./${{env.Path_Auth_API}}/ -c Release -o ${{ github.workspace }}/${{env.Path_Auth_API}}/myapp

      - name: dotnet publish coupon api
        run: dotnet publish ./${{env.Path_Coupon_API}}/ -c Release -o ${{ github.workspace }}/${{env.Path_Coupon_API}}/myapp

      - name: dotnet publish email api
        run: dotnet publish ./${{env.Path_Email_API}}/ -c Release -o ${{ github.workspace }}/${{env.Path_Email_API}}/myapp

      - name: dotnet publish product api
        run: dotnet publish ./${{env.Path_Product_API}}/ -c Release -o ${{ github.workspace }}/${{env.Path_Product_API}}/myapp

      - name: dotnet publish shopping cart api
        run: dotnet publish ./${{env.Path_ShoppingCart_API}}/ -c Release -o ${{ github.workspace }}/${{env.Path_ShoppingCart_API}}/myapp

      - name: dotnet publish web
        run: dotnet publish ./${{env.Path_Web}}/ -c Release -o ${{ github.workspace }}/${{env.Path_Web}}/myapp
        
  upload:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Upload artifact auth api
        uses: actions/upload-artifact@v4
        with:
          name: auth-api
          path: ${{ github.workspace }}/${{env.Path_Auth_API}}/myapp

      - name: Upload artifact coupon api
        uses: actions/upload-artifact@v4
        with:
          name: coupon-api
          path: ${{ github.workspace }}/${{env.Path_Coupon_API}}/myapp

      - name: Upload artifact email api
        uses: actions/upload-artifact@v4
        with:
          name: email-api
          path: ${{ github.workspace }}/${{env.Path_Email_API}}/myapp

      - name: Upload artifact product api
        uses: actions/upload-artifact@v4
        with:
          name: product-api
          path: ${{ github.workspace }}/${{env.Path_Product_API}}/myapp

      - name: Upload artifact shoppingcart api
        uses: actions/upload-artifact@v4
        with:
          name: shoppingcart-api
          path: ${{ github.workspace }}/${{env.Path_ShoppingCart_API}}/myapp

      - name: Upload artifact web
        uses: actions/upload-artifact@v4
        with:
          name: web-ui
          path: ${{ github.workspace }}/${{env.Path_Web}}/myapp
          
  download:
    runs-on: self-hosted
    needs: upload
    steps:
      - name: download artifact auth api
        uses: actions/download-artifact@v4
        with:
          name: auth-api
          path: ${{ github.workspace }}/${{env.Path_Auth_API}}/myapp

      - name: download artifact coupon api
        uses: actions/download-artifact@v4
        with:
          name: coupon-api
          path: ${{ github.workspace }}/${{env.Path_Coupon_API}}/myapp

      - name: download artifact email api
        uses: actions/download-artifact@v4
        with:
          name: email-api
          path: ${{ github.workspace }}/${{env.Path_Email_API}}/myapp

      - name: download artifact product api
        uses: actions/download-artifact@v4
        with:
          name: product-api
          path: ${{ github.workspace }}/${{env.Path_Product_API}}/myapp

      - name: download artifact shoppingcart api
        uses: actions/download-artifact@v4
        with:
          name: shoppingcart-api
          path: ${{ github.workspace }}/${{env.Path_ShoppingCart_API}}/myapp

      - name: download artifact web
        uses: actions/download-artifact@v4
        with:
          name: web-ui
          path: ${{ github.workspace }}/${{env.Path_Web}}/myapp

  deploy:
    runs-on: self-hosted
    needs: download
    steps:
      - name: Deploy to Azure - AuthAPI
        id: deploy-auth-api
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_AuthAPI_Name }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PCMAuthAPI }}
          package: ${{ github.workspace }}/${{env.Path_Auth_API}}/myapp

      - name: Deploy to Azure - Coupon API
        id: deploy-coupon-api
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_CouponAPI_Name }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PCMCouponAPI }}
          package: ${{ github.workspace }}/${{env.Path_Coupon_API}}/myapp

      - name: Deploy to Azure - Email API
        id: deploy-Email-api
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_EmailAPI_Name }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PCMEmailAPI }}
          package: ${{ github.workspace }}/${{env.Path_Email_API}}/myapp

      - name: Deploy to Azure - Product API
        id: deploy-Product-api
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_ProductAPI_Name }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PCMProductAPI }}
          package: ${{ github.workspace }}/${{env.Path_Product_API}}/myapp

      - name: Deploy to Azure - ShoppingCart API
        id: deploy-shoppingcart-api
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_ShoppingCartAPI_Name }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PCMShoppingCartAPI }}
          package: ${{ github.workspace }}/${{env.Path_ShoppingCart_API}}/myapp

      - name: Deploy to Azure - Web UI
        id: deploy-web-ui
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_Web_Name }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PCMWebUI }}
          package: ${{ github.workspace }}/${{env.Path_Web}}/myapp

      - name: completion annoucement
        run: echo "Run Completed"
      
