name: Build and deploy .Net app to an Azure Web App

env:
  AZURE_AuthAPI_Name: 'pcmauthapi'   
  AZURE_CouponAPI_Name: 'pcmcouponapi'
  AZURE_EmailAPI_Name: 'pcmemailapi'
  AZURE_ProductAPI_Name: 'pcmproductapi'
  AZURE_ShoppingCartAPI_Name: 'pcmshoppingcartapi'
  AZURE_Web_Name: 'productcouponmanagement'
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x'                 # set this to the .NET Core version to use

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: echo workspace
        run: echo "workspace - ${{ github.workspace }}"
        
      - name: dotnet publish
        run: dotnet publish -c Release -o ${{ github.workspace }}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}/myapp

  deploy:
    permissions:
      contents: none
    runs-on: self-hosted
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy to Azure - AuthAPI
        id: deploy-auth-api
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_AuthAPI_Name }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PCMAuthAPI }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Deploy to Azure - Coupon API
        id: deploy-coupon-api
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_CouponAPI_Name }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PCMCouponAPI }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Deploy to Azure - Email API
        id: deploy-Email-api
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_EmailAPI_Name }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PCMEmailAPI }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Deploy to Azure - Product API
        id: deploy-Product-api
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_ProductAPI_Name }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PCMProductAPI }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Deploy to Azure - ShoppingCart API
        id: deploy-shoppingcart-api
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_ShoppingCartAPI_Name }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PCMShoppingCartAPI }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Deploy to Azure - Web UI
        id: deploy-web-ui
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_Web_Name }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PCMWebUI }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
