name: Build and deploy .Net app to an Azure Web App

env:
  AZURE_AuthAPI_Name: 'pcmauthapi'   
  AZURE_CouponAPI_Name: 'pcmcouponapi'
  AZURE_EmailAPI_Name: 'pcmemailapi'
  AZURE_ProductAPI_Name: 'pcmproductapi'
  AZURE_ShoppingCartAPI_Name: 'pcmshoppingcartapi'
  AZURE_Web_Name: 'productcouponmanagement'
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x'                 # set this to the .NET Core version to use

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: echo workspace
        run: echo "workspace - ${{ github.workspace }}"
        
      - name: dotnet publish
        run: dotnet publish -c Release -o ${{ github.workspace }}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}/myapp
